@host-desenv = http://localhost:8080
@host = {{host-desenv}}

### Teste 1
GET http://localhost:8080 HTTP/1.1

###
GET http://localhost:8080/games HTTP/1.1
content-type: application/json

### Game By id
GET http://localhost:8080/games/2 HTTP/1.1
content-type: application/json

### Game lists
GET http://localhost:8080/lists HTTP/1.1
content-type: application/json

### Games by list
GET http://localhost:8080/lists/2/games HTTP/1.1
content-type: application/json

### List Replacement
POST {{host}}/lists/2/replacement HTTP/1.1
content-type: application/json

{
    "sourceIndex":  3,
    "destinationIndex": 1
}